name: Platformio Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish

    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Login
        run: |
          pio account login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

      - name: Publish
        run: |
          pio pkg publish --no-interactive

      - name: Save Pack
        run: |
          pio pkg pack

      - name: Upload Library Pack
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: "*.tar.gz"
          tag: ${{ github.ref }}
          overwrite: true
